name: Java CI with Maven and build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Maven
      uses: stCarolas/setup-maven@v3
      with:
        maven-version: 3.5.4     
    - uses: actions/checkout@v2
    - name: Maven build
      run: mvn clean install
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ashish-image-name:$(date +%s)
